[package]
name = "tuna"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.1", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
mysql_binlog = "0.4.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
mysql-binlog-connector-rust = "0.1.0"
rand = "0.8.5"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "mysql"] }
futures = "0.3.30"
moka = { version = "0.12", features = ["future"] }
