version: '3'
services:
  db1:
    image: mysql:8.0.27
    container_name: db1
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --binlog-format=ROW
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "9306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - './conf:/etc/mysql/conf.d'
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
