version: '3'
services:
  db1:
    image: mysql:8.0.27
    container_name: db1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: "Asia/Shanghai"
    ports:
      - "9306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - './conf/:/etc/mysql/conf.d'
    networks:
      - app-tier
  db2:
    image: mysql:8.0.27
    container_name: db2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_DATABASE: mydb2
      MYSQL_USER: user2
      MYSQL_PASSWORD: user2
    ports:
      - "13306:3306"
    volumes:
      - ./init2:/docker-entrypoint-initdb.d
      - './conf/:/etc/mysql/conf.d'
    networks:
      - app-tier
  clickhouse:
    image: clickhouse/clickhouse-server:24.7.4
    container_name: clickhouse
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: tuna
      CLICKHOUSE_USER: clickhouse-user
      CLICKHOUSE_PASSWORD: secret
    ports:
      - "8123:8123"
      - "9000:9000"
  clickhouse-init:
    image: clickhouse/clickhouse-server:24.7.4
    volumes:
      - ./init_clickhouse:/var/init_clickhouse
    depends_on:
      - clickhouse
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      while ! clickhouse-client --host clickhouse --user clickhouse-user --password secret -q \"SHOW databases;\"; do
          echo waiting for clickhouse up
          sleep 1
      done

      clickhouse-client --host clickhouse --user clickhouse-user --password secret --queries-file /var/init_clickhouse/init.sql

      tail -f /dev/null
      "
networks:
  app-tier:
    driver: bridge
