clickhouse:
  url: http://localhost:8123
  user: clickhouse-user
  password: secret
  database: tuna
mysql:
  url: mysql://root:root@localhost:9306/mydb
redis:
  urls:
    - redis://127.0.0.1:7000/
    - redis://127.0.0.1:7001/
    - redis://127.0.0.1:7002/
  password: secret
logging:
  console: false